module InvoiceImportHelper

  COLUMN_HEADERS = [
    "Customer ID",
    "Customer Name",
    "Invoice/CM #",
    "Apply to Invoice Number",
    "Credit Memo",
    "Progress Billing Invoice",
    "Date",
    "Ship By",
    "Quote",
    "Quote #",
    "Quote Good Thru Date",
    "Drop Ship",
    "Ship to Name",
    "Ship to Address-Line One",
    "Ship to Address-Line Two",
    "Ship to City",
    "Ship to State",
    "Ship to Zipcode",
    "Ship to Country",
    "Customer PO",
    "Ship Via",
    "Ship Date",
    "Date Due",
    "Discount Amount",
    "Discount Date",
    "Displayed Terms",
    "Sales Representative ID",
    "Accounts Receivable Acccount",
    "Accounts Receivable Amount",
    "Sales Tax ID",
    "Invoice Note",
    "Note Prints After Line Items",
    "Statement Note",
    "Stmt Note Prints Before Ref",
    "Internal Note",
    "Beginning Balance Transaction",
    "AR Date Cleared in Bank Rec",
    "Number of Distributions",
    "Invoice/CM Distribution",
    "Apply to Invoice Distribution",
    "Apply to Sales Order",
    "Apply to Proposal",
    "Quantity",
    "SO/Proposal Number",
    "Item ID",
    "Serial Number",
    "SO/Proposal Distribution",
    "Description",
    "G/L Account",
    "GL Date Cleared in Bank Rec",
    "Unit Price",
    "Tax Type",
    "UPC / SKU",
    "Weight",
    "Amount",
    "Inventory Account",
    "Inv Acnt Date Cleared In Bank Rec",
    "Cost of Sales Account",
    "COS Acnt Date Cleared In Bank Rec",
    "U/M ID",
    "U/M No. of Stocking Units",
    "Stocking Quantity",
    "Stocking Unit Price",
    "Cost of Sales Amount",
    "Job ID",
    "Sales Tax Agency ID",
    "Transaction Period",
    "Transaction Number",
    "Receipt Number",
    "Return Authorization",
    "Voided by Transaction",
    "Retainage Percent",
    "Recur Number",
    "Recur Frequency",
  ]

  CONSTANT_DATA = {
    "Credit Memo": "FALSE",
    "Drop Ship": "FALSE",
    "Accounts Receivable Acccount": "10200",
    "Beginning Balance Transaction": "FALSE",
    "Apply to Sales Order": "FALSE",
    "Apply to Proposal": "FALSE",
    "Tax Type": "1",
    "U/M No. of Stocking Units": "1",
  }

end
