DatabaseCleaner.clean_with :truncation

User.create(name: "Peter", email: "peter@filmmovement.com", password: "password", admin: true)
User.create(name: "Michael", email: "michael@filmmovement.com", password: "password", admin: true)

DealTemplate.create(name: "No Expenses Recouped")
DealTemplate.create(name: "Expenses Recouped From Top")
DealTemplate.create(name: "Theatrical Expenses Recouped From Top")
DealTemplate.create(name: "Expenses Recouped From Licensor Share")
DealTemplate.create(name: "GR Percentage")
DealTemplate.create(name: "GR Percentage Theatrical/Non-Theatrical")

RevenueStream.create(name: "Theatrical", order: 1)
RevenueStream.create(name: "Non-Theatrical", nickname: "Non-T", order: 2)
RevenueStream.create(name: "Video", order: 3)
RevenueStream.create(name: "Commercial Video", nickname: "C. Video", order: 4)
RevenueStream.create(name: "VOD", order: 5)
RevenueStream.create(name: "SVOD", order: 6)
RevenueStream.create(name: "TVOD", order: 7)
RevenueStream.create(name: "AVOD", order: 8)
RevenueStream.create(name: "FVOD", order: 9)
RevenueStream.create(name: "Other Internet", nickname: "Internet", order: 10)
RevenueStream.create(name: "Hotels, Ships, Airlines", nickname: "Ancillary", order: 11)
RevenueStream.create(name: "Television", nickname: "TV", order: 12)
RevenueStream.create(name: "FM Subscription", nickname: "Club", order: 13)
RevenueStream.create(name: "Jewish Festivals", nickname: "Jewish", order: 14)

Right.create(name: 'Theatrical', order: 1)
Right.create(name: 'Educational', order: 2)
Right.create(name: 'Festival', order: 3)
Right.create(name: 'Other Non-Theatrical', order: 4)
Right.create(name: 'SVOD', order: 5)
Right.create(name: 'TVOD (Cable)', order: 6)
Right.create(name: 'EST/DTR', order: 7)
Right.create(name: 'Pay TV', order: 8)
Right.create(name: 'Free TV', order: 9)
Right.create(name: 'FVOD', order: 10)
Right.create(name: 'AVOD', order: 11)
Right.create(name: 'DVD/Video', order: 12)
Right.create(name: 'Hotels', order: 13)
Right.create(name: 'Airlines', order: 14)
Right.create(name: 'Ships', order: 15)
Right.create(name: 'FM Subscription', order: 16)
